export const searchProductsWalmartBody = ({
	search_term,
}: {
	search_term: string;
}) => {
	return {
		id: "",
		dealsId: "",
		query: `${search_term}`,
		page: 1,
		prg: "desktop",
		catId: "10019",
		facet: "",
		sort: "best_match",
		rawFacet: "",
		seoPath: "",
		ps: 40,
		limit: 40,
		ptss: "",
		trsp: "",
		beShelfId: "",
		recall_set: "",
		module_search: "",
		min_price: "",
		max_price: "",
		storeSlotBooked: "",
		additionalQueryParams: {
			hidden_facet: null,
			translation: null,
			isMoreOptionsTileEnabled: true,
			isGenAiEnabled: false,
		},
		searchArgs: {
			query: `${search_term}`,
			cat_id: "10019",
			prg: "desktop",
			facet: "",
		},
		fitmentFieldParams: {
			powerSportEnabled: true,
			dynamicFitmentEnabled: true,
			extendedAttributesEnabled: false,
		},
		fitmentSearchParams: {
			id: "",
			dealsId: "",
			query: `${search_term}`,
			page: 1,
			prg: "desktop",
			catId: "",
			facet: "",
			sort: "best_match",
			rawFacet: "",
			seoPath: "",
			ps: 40,
			limit: 40,
			ptss: "",
			trsp: "",
			beShelfId: "",
			recall_set: "",
			module_search: "",
			min_price: "",
			max_price: "",
			storeSlotBooked: "",
			additionalQueryParams: {
				hidden_facet: null,
				translation: null,
				isMoreOptionsTileEnabled: true,
				isGenAiEnabled: false,
			},
			searchArgs: {
				query: `${search_term}`,
				cat_id: "",
				prg: "desktop",
				facet: "",
			},
			cat_id: "",
			_be_shelf_id: "",
		},
		enableFashionTopNav: false,
		enableRelatedSearches: false,
		enablePortableFacets: true,
		enableFacetCount: true,
		fetchMarquee: true,
		fetchSkyline: true,
		fetchGallery: false,
		fetchSbaTop: true,
		fetchDac: false,
		tenant: "CA_GLASS",
		enableFlattenedFitment: false,
		enableMultiSave: true,
		enableSellerType: true,
		enableAdditionalSearchDepartmentAnalytics: true,
		pageType: "SearchPage",
	};
};

export const searchProductWalmartHeaders = {
	authority: "www.walmart.ca",
	accept: "application/json",
	"accept-language": "en-CA",
	"content-type": "application/json",
	origin: "https://www.walmart.ca",
	referer: "https://www.walmart.ca/",
	"x-apollo-operation-name": "Search",
};
