export const searchProductsWalmartBody = ({
	search_term,
}: {
	search_term: string;
}) => {
	return {
		id: "",
		dealsId: "",
		query: `${search_term}`,
		page: 1,
		prg: "desktop",
		catId: "10019",
		facet: "",
		sort: "best_match",
		rawFacet: "",
		seoPath: "",
		ps: 40,
		limit: 40,
		ptss: "",
		trsp: "",
		beShelfId: "",
		recall_set: "",
		module_search: "",
		min_price: "",
		max_price: "",
		storeSlotBooked: "",
		additionalQueryParams: {
			hidden_facet: null,
			translation: null,
			isMoreOptionsTileEnabled: true,
			isGenAiEnabled: false,
		},
		searchArgs: {
			query: `${search_term}`,
			cat_id: "10019",
			prg: "desktop",
			facet: "",
		},
		fitmentFieldParams: {
			powerSportEnabled: true,
			dynamicFitmentEnabled: true,
			extendedAttributesEnabled: false,
		},
		fitmentSearchParams: {
			id: "",
			dealsId: "",
			query: `${search_term}`,
			page: 1,
			prg: "desktop",
			catId: "",
			facet: "",
			sort: "best_match",
			rawFacet: "",
			seoPath: "",
			ps: 40,
			limit: 40,
			ptss: "",
			trsp: "",
			beShelfId: "",
			recall_set: "",
			module_search: "",
			min_price: "",
			max_price: "",
			storeSlotBooked: "",
			additionalQueryParams: {
				hidden_facet: null,
				translation: null,
				isMoreOptionsTileEnabled: true,
				isGenAiEnabled: false,
			},
			searchArgs: {
				query: `${search_term}`,
				cat_id: "",
				prg: "desktop",
				facet: "",
			},
			cat_id: "",
			_be_shelf_id: "",
		},
		enableFashionTopNav: false,
		enableRelatedSearches: false,
		enablePortableFacets: true,
		enableFacetCount: true,
		fetchMarquee: true,
		fetchSkyline: true,
		fetchGallery: false,
		fetchSbaTop: true,
		fetchDac: false,
		tenant: "CA_GLASS",
		enableFlattenedFitment: false,
		enableMultiSave: true,
		enableSellerType: true,
		enableAdditionalSearchDepartmentAnalytics: true,
		pageType: "SearchPage",
	};
};

export const searchProductWalmartHeaders = {
	authority: "www.walmart.ca",
	accept: "application/json",
	"accept-language": "en-CA",
	"content-type": "application/json",
	origin: "https://www.walmart.ca",
	referer: "https://www.walmart.ca/",
	"x-apollo-operation-name": "Search",
};

export const query = {
	query: 'query Search( $query:String $limit:Int $page:Int $prg:Prg! $facet:String $sort:Sort = best_match $catId:String $max_price:String $min_price:String $groupIdentifier:String $spelling:Boolean = true $affinityOverride:AffinityOverride $storeSlotBooked:String $pap:String $ps:Int $ptss:String $recall_set:String $fitmentFieldParams:JSON ={}$fitmentSearchParams:JSON ={}$fetchMarquee:Boolean! $trsp:String $fetchSkyline:Boolean! $fetchGallery:Boolean! $fetchSbaTop:Boolean! $fetchDac:Boolean! $additionalQueryParams:JSON ={}$searchArgs:SearchArgumentsForCLS $enablePortableFacets:Boolean = false $enableFashionTopNav:Boolean = false $intentSource:IntentSource $tenant:String! $enableFacetCount:Boolean = true $pageType:String! = "SearchPage" $enableFlattenedFitment:Boolean = false $enableRelatedSearches:Boolean = false $enableMultiSave:Boolean = false $enableSellerType:Boolean = false $enableAdditionalSearchDepartmentAnalytics:Boolean = false ){search( query:$query limit:$limit page:$page prg:$prg pap:$pap facet:$facet sort:$sort cat_id:$catId max_price:$max_price min_price:$min_price groupIdentifier:$groupIdentifier spelling:$spelling affinityOverride:$affinityOverride storeSlotBooked:$storeSlotBooked ps:$ps ptss:$ptss recall_set:$recall_set trsp:$trsp intentSource:$intentSource additionalQueryParams:$additionalQueryParams pageType:$pageType ){query searchResult{...SearchResultFragment}}contentLayout( channel:"WWW" pageType:$pageType tenant:$tenant version:"v1" searchArgs:$searchArgs ){modules( p13n:{page:$page userReqInfo:{refererContext:{query:$query}}}){...ModuleFragment configs{__typename...on EnricherModuleConfigsV1{zoneV1}...SearchNonItemFragment...on TempoWM_GLASSWWWSponsoredProductCarouselConfigs{_rawConfigs}...on TempoWM_GLASSWWWEmailSignUpWidgetConfigs{_rawConfigs}...on _TempoWM_GLASSWWWSearchSortFilterModuleConfigs{facetsV1 @skip(if:$enablePortableFacets){...FacetFragment}topNavFacets @include(if:$enablePortableFacets){...FacetFragment}allSortAndFilterFacets @include(if:$enablePortableFacets){...FacetFragment}}...on _TempoWM_GLASSWWWSearchGuidedNavModuleConfigs{guidedNavigation{...GuidedNavFragment}}...on TempoWM_GLASSWWWBrowsingHistoryConfigs{...BrowsingHistoryFragment}...on TempoWM_GLASSWWWSearchACCStoreSelectionConfigs{ctaText userInfoMessage headingDetails{heading headingWhenFulfillmentIsSelectedAsPickup}}...on TempoWM_GLASSWWWPillsModuleConfigs{moduleSource pillsV2{...PillsModuleFragment}}...TileTakeOverProductFragment...on TempoWM_GLASSWWWSearchFitmentModuleConfigs{fitments( fitmentSearchParams:$fitmentSearchParams fitmentFieldParams:$fitmentFieldParams ){...FitmentFragment sisFitmentResponse{...SearchResultFragment}}}...on TempoWM_GLASSWWWStoreSelectionHeaderConfigs{fulfillmentMethodLabel storeDislayName}...on TempoWM_GLASSWWWBenefitProgramBannerPlaceholderConfigs{_rawConfigs}...FashionTopNavFragment @include(if:$enableFashionTopNav)...BrandAmplifierAdConfigs @include(if:$fetchSbaTop)...BannerModuleFragment...SearchNonProductBannerFragment...SearchSubscriptionBannerFragment...MarqueeDisplayAdConfigsFragment @include(if:$fetchMarquee)...SkylineDisplayAdConfigsFragment @include(if:$fetchSkyline)...GalleryDisplayAdConfigsFragment @include(if:$fetchGallery)...DynamicAdContainerConfigsFragment @include(if:$fetchDac)...HorizontalChipModuleConfigsFragment...SkinnyBannerFragment...SponsoredVideoAdFragment}}...LayoutFragment pageMetadata{location{pickupStore deliveryStore intent postalCode stateOrProvinceCode city storeId accessPointId accessType spokeNodeId}pageContext}}}fragment SearchResultFragment on SearchInterface{title aggregatedCount...BreadCrumbFragment...DebugFragment...ItemStacksFragment...SearchNonProductFragment...PageMetaDataFragment...PaginationFragment...SpellingFragment...SpanishTranslationFragment...RequestContextFragment...ErrorResponse...RelatedSearch @include(if:$enableRelatedSearches) modules{facetsV1 @skip(if:$enablePortableFacets){...FacetFragment}topNavFacets @include(if:$enablePortableFacets){...FacetFragment}allSortAndFilterFacets @include(if:$enablePortableFacets){...FacetFragment}guidedNavigation{...GuidedNavFragment}guidedNavigationV2{...PillsModuleFragment}pills{...PillsModuleFragment}spellCheck{title subTitle urlLinkText url}}pac{relevantPT{productType score}showPAC reasonCode}isModularSearch hasMorePages moduleArrayV2{...ModuleV2Fragment}}fragment ModuleV2Fragment on ModuleV2{meta{...ModularMetaV2Fragment}content{...ModularContentV2Fragment}}fragment ModularMetaV2Fragment on ModularMetaV2{beacon displayType id subType type}fragment ModularContentV2Fragment on ModularContentV2{bottomSeparator initialCount subtitle title data{...ContentDataFragment...RelatedSearchResultsFragment}items{...ModularSearchItemFragment}}fragment ModularSearchItemFragment on Product{__typename buyBoxSuppression similarItems id usItemId wfsEnabled @include(if:$enableSellerType) fitmentLabel name checkStoreAvailabilityATC seeShippingEligibility brand type shortDescription weightIncrement topResult additionalOfferCount availabilityInNearbyStore imageInfo{...ModularSearchProductImageInfoFragment}aspectInfo{name header id snippet}canonicalUrl externalInfo{url}itemType category{path{name url}}returnPolicy{returnable freeReturns returnWindow{value unitType}returnPolicyText}badges{flags{__typename...on BaseBadge{key bundleId @include(if:$enableMultiSave) text type id styleId}...on PreviouslyPurchasedBadge{id text key lastBoughtOn numBought}}tags{__typename...on BaseBadge{key text type}}groups{__typename name members{...on BadgeGroupMember{__typename id key memberType otherInfo{moqText}rank slaText styleId text type templates{regular faster unavailable}badgeContent{type value id}}...on CompositeGroupMember{__typename join memberType styleId suffix members{__typename id key memberType rank slaText styleId text type}}}}}classType averageRating numberOfReviews esrb mediaRating salesUnitType sellerId sellerName hasSellerBadge isEarlyAccessItem earlyAccessEvent annualEvent annualEventV2 availabilityStatusV2{display value}groupMetaData{groupType groupSubType numberOfComponents groupComponents{quantity offerId componentType productDisplayName}}productLocation{displayValue aisle{zone aisle}}fulfillmentSpeed offerId preOrder{...ModularSearchPreorderFragment}pac{showPAC reasonCode fulfillmentPacModule}fulfillmentSummary{storeId deliveryDate}priceInfo{...ModularSearchProductPriceInfoFragment}variantCriteria{...ModularSearchVariantCriteriaFragment}snapEligible fulfillmentTitle fulfillmentType brand manufacturerName showAtc sponsoredProduct{spQs clickBeacon spTags viewBeacon}showOptions showBuyNow quickShop quickShopCTALabel rewards{eligible state minQuantity rewardAmt promotionId selectionToken rewardMultiplierStr cbOffer term expiry description}promoDiscount{discount discountEligible discountEligibleVariantPresent promotionId promoOffer state}arExperiences{isARHome isZeekit isAROptical}eventAttributes{...ModularSearchProductEventAttributesFragment}subscription{subscriptionEligible}hasCarePlans petRx{eligible singleDispense}vision{ageGroup visionCenterApproved}showExploreOtherConditionsCTA isPreowned pglsCondition newConditionProductId preownedCondition keyAttributes{displayEnum value}}fragment ModularSearchProductImageInfoFragment on ProductImageInfo{id name thumbnailUrl size}fragment ModularSearchProductPriceInfoFragment on ProductPriceInfo{priceRange{minPrice maxPrice priceString}currentPrice{...ModularSearchProductPriceFragment priceDisplay}comparisonPrice{...ModularSearchProductPriceFragment}wasPrice{...ModularSearchProductPriceFragment}unitPrice{...ModularSearchProductPriceFragment}listPrice{...ModularSearchProductPriceFragment}savingsAmount{...ModularSearchProductSavingsFragment}shipPrice{...ModularSearchProductPriceFragment}subscriptionPrice{priceString subscriptionString}priceDisplayCodes{priceDisplayCondition finalCostByWeight submapType}wPlusEarlyAccessPrice{memberPrice{...ModularSearchProductPriceFragment}savings{...ModularSearchProductSavingsFragment}eventStartTime eventStartTimeDisplay}subscriptionDualPrice subscriptionPercentage}fragment ModularSearchPreorderFragment on PreOrder{isPreOrder preOrderMessage preOrderStreetDateMessage streetDate streetDateDisplayable streetDateType}fragment ModularSearchProductPriceFragment on ProductPrice{price priceString variantPriceString priceType currencyUnit priceDisplay}fragment ModularSearchProductSavingsFragment on ProductSavings{amount percent priceString}fragment ModularSearchProductEventAttributesFragment on EventAttributes{priceFlip specialBuy}fragment ModularSearchVariantCriteriaFragment on VariantCriterion{name type id displayName isVariantTypeSwatch variantList{id images name rank swatchImageUrl availabilityStatus products selectedProduct{canonicalUrl usItemId}}}fragment ContentDataFragment on ContentData{type name displayName url imageUrl}fragment RelatedSearchResultsFragment on RelatedSearchResults{imageUrl title url}fragment ModuleFragment on TempoModule{__typename type name version moduleId schedule{priority}matchedTrigger{zone}}fragment LayoutFragment on ContentLayout{layouts{id layout}}fragment BreadCrumbFragment on SearchInterface{breadCrumb{id name url cat_level}}fragment DebugFragment on SearchInterface{debug{sisUrl adsUrl genAIDebugInfo{searchAlgorithm isGenAiQueryEligible genAIUnavailableReason}presoDebugInformation{explainerToolsResponse}}}fragment ItemStacksFragment on SearchInterface{itemStacks{displayMessage meta{adsBeacon{adUuid moduleInfo max_ads}spBeaconInfo{adUuid moduleInfo pageViewUUID placement max}query isPartialResult stackId stackType stackName title description subTitle titleKey queryUsedForSearchResults layoutEnum totalItemCount totalItemCountDisplay viewAllParams{query cat_id sort facet affinityOverride recall_set groupIdentifier min_price max_price}borderColor iconUrl}itemsV2{...ItemFragment...InGridMarqueeAdFragment...InGridAdFragment...TileTakeOverTileFragment}content{title subtitle data{type name displayName url imageUrl}}}}fragment ItemFragment on Product{__typename buyBoxSuppression similarItems id usItemId wfsEnabled @include(if:$enableSellerType) fitmentLabel name checkStoreAvailabilityATC seeShippingEligibility brand type shortDescription weightIncrement topResult additionalOfferCount availabilityInNearbyStore imageInfo{...ProductImageInfoFragment}aspectInfo{name header id snippet}canonicalUrl externalInfo{url}itemType category{path{name url}}returnPolicy{returnable freeReturns returnWindow{value unitType}returnPolicyText}badges{flags{__typename...on BaseBadge{key bundleId @include(if:$enableMultiSave) text type id styleId}...on PreviouslyPurchasedBadge{id text key lastBoughtOn numBought}}tags{__typename...on BaseBadge{key text type}}groups{__typename name members{...on BadgeGroupMember{__typename id key memberType otherInfo{moqText}rank slaText styleId text type templates{regular faster unavailable}badgeContent{type value id}}...on CompositeGroupMember{__typename join memberType styleId suffix members{__typename id key memberType rank slaText styleId text type}}}}}classType averageRating numberOfReviews esrb mediaRating salesUnitType sellerId sellerName hasSellerBadge isEarlyAccessItem earlyAccessEvent annualEvent annualEventV2 availabilityStatusV2{display value}groupMetaData{groupType groupSubType numberOfComponents groupComponents{quantity offerId componentType productDisplayName}}productLocation{displayValue aisle{zone aisle}}fulfillmentSpeed offerId preOrder{...PreorderFragment}pac{showPAC reasonCode fulfillmentPacModule}fulfillmentSummary{storeId deliveryDate}priceInfo{...ProductPriceInfoFragment}variantCriteria{...VariantCriteriaFragment}snapEligible fulfillmentTitle fulfillmentType brand manufacturerName showAtc sponsoredProduct{spQs clickBeacon spTags viewBeacon}showOptions showBuyNow quickShop quickShopCTALabel rewards{eligible state minQuantity rewardAmt promotionId selectionToken rewardMultiplierStr cbOffer term expiry description}promoDiscount{discount discountEligible discountEligibleVariantPresent promotionId promoOffer state}arExperiences{isARHome isZeekit isAROptical}eventAttributes{...ProductEventAttributesFragment}subscription{subscriptionEligible}hasCarePlans petRx{eligible singleDispense}vision{ageGroup visionCenterApproved}showExploreOtherConditionsCTA isPreowned pglsCondition newConditionProductId preownedCondition keyAttributes{displayEnum value}}fragment ProductImageInfoFragment on ProductImageInfo{id name thumbnailUrl size}fragment ProductPriceInfoFragment on ProductPriceInfo{priceRange{minPrice maxPrice priceString}currentPrice{...ProductPriceFragment priceDisplay}comparisonPrice{...ProductPriceFragment}wasPrice{...ProductPriceFragment}unitPrice{...ProductPriceFragment}listPrice{...ProductPriceFragment}savingsAmount{...ProductSavingsFragment}shipPrice{...ProductPriceFragment}subscriptionPrice{priceString subscriptionString}priceDisplayCodes{priceDisplayCondition finalCostByWeight submapType}wPlusEarlyAccessPrice{memberPrice{...ProductPriceFragment}savings{...ProductSavingsFragment}eventStartTime eventStartTimeDisplay}subscriptionDualPrice subscriptionPercentage}fragment PreorderFragment on PreOrder{isPreOrder preOrderMessage preOrderStreetDateMessage streetDate streetDateDisplayable streetDateType}fragment ProductPriceFragment on ProductPrice{price priceString variantPriceString priceType currencyUnit priceDisplay}fragment ProductSavingsFragment on ProductSavings{amount percent priceString}fragment ProductEventAttributesFragment on EventAttributes{priceFlip specialBuy}fragment VariantCriteriaFragment on VariantCriterion{name type id displayName isVariantTypeSwatch variantList{id images name rank swatchImageUrl availabilityStatus products selectedProduct{canonicalUrl usItemId}}}fragment InGridMarqueeAdFragment on MarqueePlaceholder{__typename type moduleLocation lazy}fragment InGridAdFragment on AdPlaceholder{__typename type moduleLocation lazy adUuid hasVideo moduleInfo}fragment TileTakeOverTileFragment on TileTakeOverProductPlaceholder{__typename type tileTakeOverTile{span title subtitle image{src alt assetId assetName}logoImage{src alt}backgroundColor titleTextColor subtitleTextColor tileCta{ctaLink{clickThrough{value}linkText title}ctaType ctaTextColor}adsEnabled adCardLocation enableLazyLoad}}fragment SearchNonProductFragment on SearchInterface{nonProduct{title image imageAlt displayName description url urlAlt}}fragment PageMetaDataFragment on SearchInterface{pageMetadata{storeSelectionHeader{fulfillmentMethodLabel storeDislayName}title canonical source description location{addressId}subscriptionEligible}}fragment PaginationFragment on SearchInterface{paginationV2{maxPage pageProperties}}fragment SpanishTranslationFragment on SearchInterface{translation{metadata{originalQuery translatedQuery isTranslated translationOfferType moduleSource}translationModule{title urlLinkText originalQueryUrl}}}fragment SpellingFragment on SearchInterface{spelling{correctedTerm}}fragment RequestContextFragment on SearchInterface{requestContext{vertical hasGicIntent isFitmentFilterQueryApplied searchMatchType categories{id name}}}fragment ErrorResponse on SearchInterface{errorResponse{correlationId source errorCodes errors{errorType statusCode statusMsg source}}}fragment GuidedNavFragment on GuidedNavigationSearchInterface{title url}fragment PillsModuleFragment on PillsSearchInterface{title titleColor url image:imageV1{src alt assetId assetName}}fragment BrowsingHistoryFragment on TempoWM_GLASSWWWBrowsingHistoryConfigs{title products{id usItemId imageInfo{thumbnailUrl}classType canonicalUrl name}}fragment BannerViewConfigFragment on BannerViewConfigCLS{title image imageAlt displayName description url urlAlt appStoreLink appStoreLinkAlt playStoreLink playStoreLinkAlt}fragment BannerModuleFragment on TempoWM_GLASSWWWSearchBannerConfigs{moduleType viewConfig{...BannerViewConfigFragment}}fragment SearchNonProductBannerFragment on TempoWM_GLASSWWWSearchNonProductBannerConfigs{nps{query normalisedQuery nonProduct{title image imageAlt displayName description url urlAlt}}viewConfig{...BannerViewConfigFragment}}fragment SearchSubscriptionBannerFragment on TempoWM_GLASSWWWSearchSubscriptionBannerConfigs{viewConfig{...BannerViewConfigFragment}}fragment FacetFragment on Facet{title name expandOnLoad type displayType layout min max selectedMin selectedMax unboundedMax stepSize isSelected values{id title name expandOnLoad description type itemCount @include(if:$enableFacetCount) isSelected baseSeoURL catPathName @include(if:$enableAdditionalSearchDepartmentAnalytics) values{id title name expandOnLoad description type itemCount @include(if:$enableFacetCount) isSelected baseSeoURL values{id title name expandOnLoad description type itemCount @include(if:$enableFacetCount) isSelected baseSeoURL values{id title name expandOnLoad description type itemCount @include(if:$enableFacetCount) isSelected baseSeoURL values{id title name expandOnLoad description type itemCount @include(if:$enableFacetCount) isSelected baseSeoURL values{id title name expandOnLoad description type itemCount @include(if:$enableFacetCount) isSelected baseSeoURL values{id title name expandOnLoad description type itemCount @include(if:$enableFacetCount) isSelected baseSeoURL values{id title name expandOnLoad description type itemCount @include(if:$enableFacetCount) isSelected baseSeoURL}}}}}}}}}fragment FitmentFragment on Fitments{partTypeIDs fitmentType isNarrowSearch fitmentOptionalFields{...FitmentFieldFragment}result{fitmentType status formId position quantityTitle extendedAttributes{...FitmentFieldFragment}labels{...LabelFragment}resultSubTitle notes suggestions{...FitmentSuggestionFragment}}redirectUrl{title clickThrough{value}}labels{...LabelFragment}savedVehicle{vehicleType{...VehicleFieldFragment}vehicleYear{...VehicleFieldFragment}vehicleMake{...VehicleFieldFragment}vehicleModel{...VehicleFieldFragment}additionalAttributes{...VehicleFieldFragment}}fitmentFields{...VehicleFieldFragment}fitmentForms{id fields{...FitmentFieldFragment}title labels{...LabelFragment}garage{vehicles{...AutoVehicle}}}}fragment LabelFragment on FitmentLabels{ctas{...FitmentLabelEntityFragment}messages{...FitmentLabelEntityFragment}links{...FitmentLabelEntityFragment}images{...FitmentLabelEntityFragment}}fragment FitmentLabelEntityFragment on FitmentLabelEntity{id label labelV1 @include(if:$enableFlattenedFitment)}fragment VehicleFieldFragment on FitmentVehicleField{id label value}fragment FitmentFieldFragment on FitmentField{id displayName value extended data{value label}dependsOn isRequired errorMessage}fragment FitmentSuggestionFragment on FitmentSuggestion{id position loadIndex speedRating searchQueryParam labels{...LabelFragment}cat_id fitmentSuggestionParams{id value}optionalSuggestionParams{id value displayName data{label value}dependsOn isRequired errorMessage}applicationSuggestionParams{position}}fragment MarqueeDisplayAdConfigsFragment on TempoWM_GLASSWWWMarqueeDisplayAdConfigs{_rawConfigs ad{...DisplayAdFragment}}fragment DisplayAdFragment on Ad{...AdFragment adContent{type data{__typename...AdDataDisplayAdFragment}}}fragment AdFragment on Ad{status moduleType platform pageId pageType storeId stateCode zipCode pageContext moduleConfigs adsContext adRequestComposite}fragment AdDataDisplayAdFragment on AdData{...on DisplayAd{json status}}fragment GalleryDisplayAdConfigsFragment on TempoWM_GLASSWWWGalleryDisplayAdConfigs{_rawConfigs}fragment SkylineDisplayAdConfigsFragment on TempoWM_GLASSWWWSkylineDisplayAdConfigs{_rawConfigs ad{...SkylineDisplayAdFragment}}fragment SkylineDisplayAdFragment on Ad{...SkylineAdFragment adContent{type data{__typename...SkylineAdDataDisplayAdFragment}}}fragment SkylineAdFragment on Ad{status moduleType platform pageId pageType storeId stateCode zipCode pageContext moduleConfigs adsContext adRequestComposite}fragment SkylineAdDataDisplayAdFragment on AdData{...on DisplayAd{json status}}fragment DynamicAdContainerConfigsFragment on TempoWM_GLASSWWWDynamicAdContainerConfigs{_rawConfigs adModules{moduleType moduleLocation priority adServers{adServer}}zoneLocation lazy}fragment BrandAmplifierAdConfigs on TempoWM_GLASSWWWBrandAmplifierAdConfigs{_rawConfigs moduleLocation ad{...SponsoredBrandsAdFragment}}fragment SponsoredBrandsAdFragment on Ad{...AdFragment adContent{type data{__typename...AdDataSponsoredBrandsFragment}}}fragment AdDataSponsoredBrandsFragment on AdData{...on SponsoredBrands{adUuid adExpInfo moduleInfo brands{logo{featuredHeadline featuredImage featuredImageName featuredUrl logoClickTrackUrl}products{...ProductFragment}}}}fragment ProductFragment on Product{usItemId offerId badges{flags{__typename...on BaseBadge{id text key query type styleId}...on PreviouslyPurchasedBadge{id text key lastBoughtOn numBought criteria{name value}}}labels{__typename...on BaseBadge{id text key}...on PreviouslyPurchasedBadge{id text key lastBoughtOn numBought}}tags{__typename...on BaseBadge{id text key}}groups{__typename name members{...on BadgeGroupMember{__typename id key memberType rank slaText styleId text type}...on CompositeGroupMember{__typename join memberType styleId suffix members{__typename id key memberType rank slaText styleId text type}}}}}priceInfo{priceDisplayCodes{rollback reducedPrice eligibleForAssociateDiscount clearance strikethrough submapType priceDisplayCondition unitOfMeasure pricePerUnitUom}currentPrice{price priceString priceDisplay}wasPrice{price priceString}listPrice{price priceString}priceRange{minPrice maxPrice priceString}unitPrice{price priceString}savingsAmount{priceString}comparisonPrice{priceString}subscriptionPrice{priceString subscriptionString price minPrice maxPrice intervalFrequency duration percentageRate durationUOM interestUOM}wPlusEarlyAccessPrice{memberPrice{price priceString priceDisplay}savings{amount priceString}eventStartTime eventStartTimeDisplay}}annualEventV2 earlyAccessEvent isEarlyAccessItem eventAttributes{priceFlip specialBuy}snapEligible showOptions sponsoredProduct{spQs clickBeacon spTags}canonicalUrl numberOfReviews averageRating availabilityStatus imageInfo{thumbnailUrl allImages{id url}}name fulfillmentBadge classType type showAtc brand}fragment SearchNonItemFragment on TempoWM_GLASSWWWSearchNonItemConfigs{title subTitle urlLinkText url}fragment HorizontalChipModuleConfigsFragment on TempoWM_GLASSWWWHorizontalChipModuleConfigs{chipModuleSource:moduleSource heading headingColor backgroundImage{src alt}backgroundColor desktopImageHeight desktopImageWidth mobileImageHeight mobileImageWidth chipModule{title url{linkText title clickThrough{type value}}}chipModuleWithImages{title titleColor url{linkText title clickThrough{type value}}image{assetId assetName alt clickThrough{type value}height src title width}}}fragment SkinnyBannerFragment on TempoWM_GLASSWWWSkinnyBannerConfigs{campaignsV1{bannerType desktopBannerHeight bannerImage{src title alt assetId assetName}mobileBannerHeight mobileImage{src title alt assetId assetName}clickThroughUrl{clickThrough{value}}backgroundColor heading{title fontColor}subHeading{title fontColor}bannerCta{ctaLink{linkText clickThrough{value}}textColor ctaType}}}fragment TileTakeOverProductFragment on TempoWM_GLASSWWWTileTakeOverProductConfigs{dwebSlots mwebSlots overrideDefaultTiles TileTakeOverProductDetailsV1{pageNumber span dwebPosition mwebPosition title subtitle image{src alt assetId assetName}logoImage{src alt}backgroundColor titleTextColor subtitleTextColor tileCta{ctaLink{clickThrough{value}linkText title uid}ctaType ctaTextColor}adsEnabled adCardLocation enableLazyLoad}}fragment FashionTopNavFragment on TempoWM_GLASSWWWCategoryTopNavConfigs{navHeaders{header{linkText clickThrough{value}}headerImageGroup{headerImage{alt src assetId assetName}imgTitle imgSubText imgLink{linkText title clickThrough{value}}}categoryGroup{category{linkText clickThrough{value}}startNewColumn subCategoryGroup{subCategory{linkText clickThrough{value}}isBold openInNewTab}}}}fragment RelatedSearch on SearchInterface{relatedSearch{title url imageUrl}}fragment AutoVehicle on AutoVehicle{cid color default documentType fitment{baseBodyType baseVehicleId driveType{id name}engineOptions{id isSelected label}smartSubModel tireSizeOptions{diameter isCustom isSelected loadIndex positions ratio speedRating tirePressureFront tirePressureRear tireSize width}trim}isDually licensePlate licensePlateState licensePlateStateCode make model reminders{id}source sourceType subModel{subModelId subModelName}subModelOptions{subModelId subModelName}vehicleId vehicleType vin year}fragment SponsoredVideoAdFragment on TempoWM_GLASSWWWSponsoredVideoAdConfigs{__typename sponsoredVideoAd{ad{adContent{data{...on SponsoredVideos{adUuid hasVideo moduleInfo}}}}}}',
	variables: {
		id: "",
		dealsId: "",
		query: "buttermilk",
		page: 1,
		prg: "desktop",
		catId: "10019",
		facet: "",
		sort: "best_match",
		rawFacet: "",
		seoPath: "",
		ps: 40,
		limit: 40,
		ptss: "",
		trsp: "",
		beShelfId: "",
		recall_set: "",
		module_search: "",
		min_price: "",
		max_price: "",
		storeSlotBooked: "",
		additionalQueryParams: {
			hidden_facet: null,
			translation: null,
			isMoreOptionsTileEnabled: true,
			isGenAiEnabled: false,
		},
		searchArgs: {
			query: "buttermilk",
			cat_id: "10019",
			prg: "desktop",
			facet: "",
		},
		fitmentFieldParams: {
			powerSportEnabled: true,
			dynamicFitmentEnabled: true,
			extendedAttributesEnabled: false,
		},
		fitmentSearchParams: {
			id: "",
			dealsId: "",
			query: "buttermilk",
			page: 1,
			prg: "desktop",
			catId: "10019",
			facet: "",
			sort: "best_match",
			rawFacet: "",
			seoPath: "",
			ps: 40,
			limit: 40,
			ptss: "",
			trsp: "",
			beShelfId: "",
			recall_set: "",
			module_search: "",
			min_price: "",
			max_price: "",
			storeSlotBooked: "",
			additionalQueryParams: {
				hidden_facet: null,
				translation: null,
				isMoreOptionsTileEnabled: true,
				isGenAiEnabled: false,
			},
			searchArgs: {
				query: "buttermilk",
				cat_id: "10019",
				prg: "desktop",
				facet: "",
			},
			cat_id: "10019",
			_be_shelf_id: "",
		},
		enableFashionTopNav: false,
		enableRelatedSearches: false,
		enablePortableFacets: true,
		enableFacetCount: true,
		fetchMarquee: true,
		fetchSkyline: true,
		fetchGallery: false,
		fetchSbaTop: true,
		fetchDac: false,
		tenant: "CA_GLASS",
		enableFlattenedFitment: false,
		enableMultiSave: true,
		enableSellerType: true,
		enableAdditionalSearchDepartmentAnalytics: true,
		pageType: "SearchPage",
	},
};
