version: "3.8"
services:
    node-app:
        container_name: node-service
        restart: unless-stopped
        build:
            context: .
        env_file:
            - .env
        command: npm run start

    caddy:
        image: caddy:2.7.6
        restart: unless-stopped
        container_name: caddy-service
        ports:
            - "80:80"
            - "443:443"
            #- "443:443/udp"
        volumes:
            - ./caddy/Caddyfile:/etc/caddy/Caddyfile
            - ./site:/srv
            - caddy_data:/data
            - caddy_config:/config

volumes:
    caddy_data:
    caddy_config:
