version: "3.8"
services:
    node-app:
        container_name: node-service
        restart: unless-stopped
        build:
            context: .
        env_file:
            - .env
        command: npm run start

    caddy:
        image: caddy:2.7.6
        restart: unless-stopped
        container_name: caddy-service
        ports:
            - "80:80"
            - "443:443"
            #- "443:443/udp"
        volumes:
            - ./caddy/prod/Caddyfile:/etc/caddy/Caddyfile
            - ./site:/srv
            - caddy_data:/data
            - caddy_config:/config
    # redis:
    #     image: redis:latest
    #     restart: unless-stopped
    #     ports:
    #         - "6379:6379"
    #     volumes:
    #         # - /path/to/local/d–∞ta:/root/redis
    #         # - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    #         - redis_data:/data

    #     environment:
    #         - REDIS_PASSWORD=my-password
    #         - REDIS_PORT=6379
    #         - REDIS_DATABASES=16
volumes:
    caddy_data:
    caddy_config:
