version: "3"
services:
  node-app:
    build:
      context: .
      # args:
      #   NODE_ENV: production
    # environment:
    #   - NODE_ENV=production
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: npm run start