version: "3.8"
services:
  node-app:
    build:
      context: .
    env_file:
      - .env
    command: npm run start
    restart: unless-stopped
      
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt