version: "3.8"
services:
    node-app:
        container_name: node-service
        hostname: node-service-prod
        image: ghcr.io/smartgrocer/sg-backend:latest
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - ./logs:/app/logs

    caddy:
        image: caddy:2.7.6
        restart: unless-stopped
        container_name: caddy-service
        ports:
            - "80:80"
            - "443:443"
            #- "443:443/udp"
        volumes:
            - ./caddy/prod/Caddyfile:/etc/caddy/Caddyfile
            - ./site:/srv
            - caddy_data:/data
            - caddy_config:/config
volumes:
    caddy_data:
    caddy_config:
