version: "3.8"
services:
  caddy:
    image: caddy:2.7.6
    restart: unless-stopped
    ports:
    #  - "3000:3000"
       - "80:80"
       - "443:443"
    volumes:
      - "../.config/caddy/panda:/etc/caddy"
      - "caddy_data:/data"
      - "caddy_config:/config"
    networks:
      - coolify

  #   noip:
  #     image: aanousakis/no-ip:latest
  #     container_name: noip
  #     restart: unless-stopped
  #     env_file:
  #       - ../.env
  #     environment:
  #       - NOIP_USERNAME="${NOIP_USERNAME}"
  #       - NOIP_PASSWORD="${NOIP_PASSWORD}"
  #       - NOIP_HOSTNAME="${NOIP_HOSTNAME}"

  #   portainer:
  #     image: portainer/portainer-ce:latest
  #     ports:
  #       - 9443:9443
  #     volumes:
  #       - data:/data
  #       - /var/run/docker.sock:/var/run/docker.sock
  #     restart: unless-stopped

  scrapper1:
    image: amerkurev/scrapper:latest
    volumes:
      - ./user_data:/home/user/user_data
      - ./user_scripts:/home/user/user_scripts
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - coolify

#   scrapper2:
#     image: amerkurev/scrapper:latest
#     volumes:
#       - ./user_data:/home/user/user_data
#       - ./user_scripts:/home/user/user_scripts
#     restart: unless-stopped

#   uptime-kuma:
#     image: louislam/uptime-kuma:1
#     container_name: uptime-kuma
#     volumes:
#       - ./uptime-kuma-data:/app/data
#     ports:
#       - 3001:3001
#     restart: always

volumes:
  data:
  caddy_data:
  caddy_config:

networks:
  coolify:
    external: true
